run:
	deno run --unstable --allow-read --allow-write --allow-run --allow-env --allow-net install/install.ts

print:
	deno run --unstable --allow-read --allow-write install/print.ts

depgraph:
	deno run --unstable --allow-read --allow-write --allow-run install/dep-graph.ts