run:
	deno run --unstable --allow-read --allow-write install/install.ts

print:
	deno run --unstable --allow-read --allow-write install/print.ts

e:
	deno run --unstable --allow-read --allow-write --allow-run install/e.ts