#!/usr/bin/env zsh
#          _  _
#    __ _ | |(_)  __ _  ___   ___  ___
#   / _` || || | / _` |/ __| / _ \/ __|
#  | (_| || || || (_| |\__ \|  __/\__ \
#   \__,_||_||_| \__,_||___/ \___||___/
#


# =================================================================
#                           Navigation
# =================================================================
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ~="cd ~"
alias -- -="cd -"


# =================================================================
#                          Environment
# =================================================================
alias path='echo $PATH | tr -s ":" "\n"'


# =================================================================
#                            Hardware
# =================================================================

# not used on PopOS
# alias notebook="xrandr --output eDP1 --auto --output DP2 --off"
# alias monitor="xrandr --output eDP1 --off --output DP2 --auto"
# alias dual="xrandr --output eDP1 --auto --left-of DP2 --output DP2 --auto"
# alias mirror="xrandr --output eDP1 --auto --same-as DP2 --output DP2 --auto"


# =================================================================
#                            Listing
# =================================================================
alias l="LC_COLLATE=c ls -F -1 --show-control-chars --color --group-directories-first"
alias ls="LC_COLLATE=c ls -F -1 --show-control-chars --color --group-directories-first"
alias ll="LC_COLLATE=c ls -lhF --show-control-chars --color --group-directories-first --time-style='+%d.%m.%Y %H:%M'"
alias la="LC_COLLATE=c ls -lhFA --show-control-chars --color --group-directories-first --time-style='+%d.%m.%Y %H:%M'"

alias le="less -FiMRX"
alias lesf="less +F"
alias bat="batcat"

alias df="df -h /"
alias tree="tree -I 'node_modules|.git'"


# =================================================================
#                            Editing
# =================================================================
alias e="$EDITOR"
alias evimrc="$EDITOR ~/dotfiles/vimrc"
alias ezsh="$EDITOR ~/dotfiles/zshrc"
alias eenv="$EDITOR ~/dotfiles/zshenv"
alias ealias="$EDITOR ~/dotfiles/aliases"
alias efunc="$EDITOR ~/dotfiles/functions"
alias eterm="$EDITOR ~/dotfiles/kitty.conf"
alias ,fe="nvim -c \"lua require('telescope.builtin').oldfiles({ previewer = false })\""

# =================================================================
#                            Scripts
# =================================================================
alias p="project"
alias ias="ia-search"
alias iaf="ia-file"

# =================================================================
#                          Directories
# =================================================================
alias home="cd ~"
alias repo="cd ~/code"
alias lutr="cd ~/code/lukastrumm"
alias learn="cd ~/code/learning-progress"
alias dotf="cd ~/dotfiles"
alias down="cd ~/Downloads"
alias drop="cd ~/Dropbox"
alias sand="cd ~/sandbox"
alias iad="cd ~/ia"

# =================================================================
#                         npm, node, deno
# =================================================================

alias nb="npm run build"
alias nd="npm run dev"
alias ni="npm install"
alias nid="npm install --save-dev"
alias nl="npm run lint"
alias nr="npm run"
alias ns="npm start"
alias nse="npm run serve"
alias nt="npm run --silent test"
alias nuni="npm uninstall"
alias nv="npm run validate"
alias nw="npm run watch"

alias pn="pnpm"

alias dt="deno task"

alias deps="cat package.json | json dependencies | json --items -a key value | sed 's/ /|/' | column -s '|' -t"
alias devdeps="cat package.json | json devDependencies | json --items -a key value | sed 's/ /|/' | column -s '|' -t"
alias scripts="cat package.json | json scripts | json --items -a key value | sed 's/ /|/' | column -s '|' -t"

alias mit="npx mit-license --name 'Lukas Trumm'"

# =================================================================
#                         Other programs
# =================================================================

alias apti="sudo apt-get install -y"
alias apts="apt search"
alias aptu="sudo apt-get update"
alias bsync="browser-sync start --server --files . --no-notify --open ."
alias cal="LC_TIME=cs_CZ.UTF-8 ncal -MC" # Show czech calendar with Monday as the first day of a week
alias copy="xsel -b"
alias d="docker"
alias dc="docker-compose"
alias ht="http --verify=no"
alias ipy="ipython"
alias md="cli-md"
alias py="python"
alias tp="trash-put"
alias vag="vagrant"
alias xmlstar="xmlstarlet"

# =================================================================
#                              Git
# =================================================================


git_default_branch() {
    local branch
    # First look for my custom file named 'deafult_branch' in the git repo,
    # where the name of the default branch should be specified
    for dir in "." ".." "../.." "../../.."; do
        key_file=$dir/.git/default_branch
        if [ -f "$key_file" ]; then 
            branch=`cat "$key_file"`
            break
        fi
    done
    if [ -z "$branch" ]; then
        branch=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's#^refs/remotes/origin/##')
    elif [ -z "$branch" ]; then
        branch=$(git remote show origin 2>/dev/null | grep "HEAD branch" | cut -d ":" -f 2)
    elif [ -z "$branch" ]; then
        branch="master"
    fi
    echo $branch
}

gcom() {
    git switch $(git_default_branch)
}

alias ga="git add"
alias gaa="git add --all"
alias gco="git switch"
alias gcob="git switchit"
alias gcan="git commit --amend --no-edit"
alias galiases="git config --global --includes --get-regexp alias"
alias gd="git diff -- . ':!package-lock.json' ':!yarn.lock' ':!pnpm-lock.yaml'"
alias gds="git diff --staged -- . ':!package-lock.json' ':!yarn.lock' ':!pnpm-lock.yaml'"
alias gdw="git diff --color-words"

alias gchanged="git update-index --no-assume-unchanged"
alias gunchanged="git update-index --assume-unchanged"
alias glistunchanged="git ls-files -v|grep '^[[:lower:]]'"
alias gignored="git ls-files --other --ignored --exclude-standard"

logformat='log --graph --abbrev-commit --decorate --format=format:"%C(yellow)%h%C(reset) %C(cyan)%ci%x08%x08%x08%x08%x08%x08%x08%x08%x08%C(reset) %s %C(green)(%an)%C(reset)%C(bold green)%d%C(reset)"'

alias gl="git log --graph --decorate --oneline -n15"
alias gla="git log --graph --decorate --oneline"
alias gle="git log --graph --decorate --oneline --all -n15"
alias glea="git log --graph --decorate --oneline --all"
alias glmy="git log --graph --decorate --oneline --all -n15 --author=\"Lukas Trumm\""
alias glf="git $logformat -n8 --name-status"
alias gm="git $logformat -n15"
alias gma="git $logformat"
alias gme="git $logformat --all -n15"
alias gmea="git $logformat --all"
alias gmmy="git $logformat --all -n15 --author=\"Lukas Trumm\""
alias gfh="git $logformat --all --follow" # file history
alias gsf="git show --name-status"
alias gfe="git fetch"
alias gup="git stash save -u && git pull && git stash pop"
alias gre="git restore"
alias gre.="git restore ."
alias gres='git restore --staged'
alias greb="git rebase"
git-rem() { git rebase `git_default_branch` }
alias grem="git-rem"
alias grec="git rebase --continue"
git-fem() { git fetch origin `git_default_branch`:`git_default_branch`; git log --oneline `git_default_branch` @{1}..`git_default_branch` }
alias gfem="git-fem"
alias gst="git status"
alias gs="git status -s"
alias grs="git recursive-status"
alias gpu='[[ -z $(git config "branch.$(git symbolic-ref --short HEAD).merge") ]] && git push -u origin $(git symbolic-ref --short HEAD) || git push'
alias gul='git pull'
alias gundo='git reset --mixed HEAD~'
alias standup="git-standup"
alias myweek="git standup -d 8 -D 'short'"
git-gogo() { git checkout `git_default_branch` && git pull && git gone }
alias gogo="git-gogo"
alias i="issue"
alias il="gh issue list"
alias ila="gh issue list --state all"
alias gmt="git mergetool"

# =================================================================
#                              Lists
# =================================================================

alias zshkeys="cat ~/.zshrc | rg '# Alt' | sed 's/^# //'"

targets() {
  make -qp | awk -F':' '/^[a-zA-Z0-9][^$#\/\t=]*:([^=]|$)/ {split($1,A,/ /);for(i in A)print A[i]}' | sort -u | grep -v "Makefile\|Linux\|Darwin"
}

alias mak="targets"


# =================================================================
#                             Search
# =================================================================
# alias rg='rg ...'


# =================================================================
#                          Zsh aliases
# =================================================================

if [[ $(echo $0) =~ "zsh" ]]; then

  alias -g G="| grep -i"
  alias -g H="| head"
  alias -g T="| tail"
  alias -g L="| less -FiMRX"
  alias -g R="| rg"
  alias -g C="| wc -l"
  alias -g F="| fpp"
  alias -g IN="..@{u}"
  alias -g OUT="@{u}.."
  alias -g UP="@{u}"

  # Images
  alias -s gif=gthumb
  alias -s jpg=gthumb
  alias -s png=gthumb

  # Text
  alias -s css=$EDITOR
  alias -s java=$EDITOR
  alias -s js=$EDITOR
  alias -s md=$EDITOR
  alias -s php=$EDITOR
  alias -s txt=$EDITOR

fi
