#!/usr/bin/env bash

# Right click
if [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    notify-send -u low "$(head -1 $HOME/.adhoc | cut -c 30)" 
fi

ADHOC_BLOCK=$(head -1 $HOME/.adhoc | cut -c 1-10)

echo "$ADHOC_BLOCK  "
