#!/usr/bin/env bash


# Right click
if [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    PING_TIME="Ping: $(ping -c1 8.8.8.8 | grep 'time=' | sed 's/.*time=//')"
    IP_ADDR_INT="Internal IP: $(. /usr/share/i3blocks/iface | head -1)"
    IP_ADDR_OUT="External IP: $(curl ipinfo.io/ip)"
    notify-send -u low "Network status" "$PING_TIME\n$IP_ADDR_INT\n$IP_ADDR_OUT"
fi

ping -c1 8.8.8.8 > /dev/null

if [[ $? -eq 0 ]]; then
	echo 
else
	echo 
fi
