#!/usr/bin/env bash


battery_status=$(acpi -b)
percentage=$(acpi -b | awk -F, '{print $2}' | tr -d ' %')

# Right click
if [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
    notify-send -u low "Battery status" "$(acpi -b | cut -d: -f2- | sed 's/^\ //')"
fi

[[ "$battery_status" =~ "No support" ]] && exit 0


[[ -z "$battery_status" ]] && [[ -z "$percentage" ]] && echo "" && exit 0


if [[ "${battery_status}" =~ "Charging" ]]; then
    echo 
elif [[ "${percentage}" -lt 10 ]]; then
    echo 
elif [[ "${percentage}" -lt 30 ]]; then
    echo 
elif [[ "${percentage}" -lt 55 ]]; then
    echo 
elif [[ "${percentage}" -lt 80 ]]; then
    echo 
else
    echo 
fi

