#!/usr/bin/env bash

VPN1=$(nmcli c | awk '$3=="vpn" && $4!="--" {printf $1}')

[ -n "$VPN1" ] && echo -n "$VPN1 "


VPNC=$(ps aux | grep vpnc | grep -v grep | awk '{printf $NF}')

[ -n "$VPNC" ] && echo -n "$VPNC "
