require "packages"
require "settings"
require "autocommands"
require "commands"
require "functions"
require "lsp-settings"
require "completion"
require "comments"
require "keybindings"
require "formatting"
require "theme"

require "user.telescope"
