- defaults:
    link:
        relink: true
        create: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore: agignore
    ~/.config/dunst/dunstrc: dunstrc
    ~/.gitconfig: gitconfig
    ~/.ideavimrc: ideavimrc
    ~/.kdiff3rc: kdiff3rc
    ~/.tmux.conf: tmux.conf
    ~/.vimrc: vimrc
    ~/.vrapperrc: vrapperrc
    ~/.Xresources: Xresources
    ~/.zshenv: zshenv
    ~/.zshrc: zshrc

    ~/.i3: i3
    ~/.vim/colors: vim/colors
    ~/.vim/syntax: vim/syntax
    ~/.vim/snippets: vim/snippets

    ~/bin : bin

    ~/.gtkrc-2.0-gnome-color-chooser:
        colors/gtkrc-2.0-gnome-color-chooser

    ~/.config/mc:
        path: ../Dropbox/conf/mc

    ~/.kde/share/config/krusaderrc:
        path: ../Dropbox/conf/krusader/krusaderrc
    ~/.kde/share/apps/krusader/krbookmarks.xml:
        path: ../Dropbox/conf/krusader/krbookmarks.xml
    ~/.kde/share/apps/krusader/krusaderui.rc:
        path: ../Dropbox/conf/krusader/krusaderui.rc
    ~/.kde/share/apps/krusader/useractions.xml:
        path: ../Dropbox/conf/krusader/useractions.xml

    ~/.fonts:
        path: ../Dropbox/conf/fonts

