#!/usr/bin/env bash

battery_status=$(acpi -b)
percentage=$(acpi -b | awk -F, '{print $2}' | tr -d ' %')


[[ "$battery_status" =~ "No support" ]] && exit 0


[[ -z "$battery_status" ]] && [[ -z "$percentage" ]] && echo "!"


if [[ "${battery_status}" =~ "Charging" ]]; then
    echo 
elif [[ "${percentage}" -lt 10 ]]; then
    echo 
elif [[ "${percentage}" -lt 30 ]]; then
    echo 
elif [[ "${percentage}" -lt 55 ]]; then
    echo 
elif [[ "${percentage}" -lt 80 ]]; then
    echo 
else
    echo 
fi

