#!/usr/bin/env bash

handle_selection() {
    if [[ "$1" ]]; then
        name="$1"
        if [[ -f "$name" ]]; then
            ( xdg-open "$name" &>/dev/null & )
        else
            notify-send -u low "File" "No file called $name."
        fi
    fi
}

handle_selection "$(locate_documents | rofi -dmenu -i -fuzzy -p "doc: ")"
