#!/usr/bin/env bash

if [[ $(hostname) == 'lt-nb-ubuntu' ]]; then
    # skype &
    # evolution &
fi


# default would be the first listed xrandr output
# OUTPUT=$(xrandr --current | grep ' connected' | awk 'NR==1 {print $1}')
# SECONDARY=$(xrandr --current | grep ' connected' | awk 'NR==2 {print $1}')

# if [[ $(hostname) == 'lukas-pc-ubuntu' ]]; then
#     :
# elif [[ $(hostname) == 'lt-nb-ubuntu' ]]; then

#     PORT='VGA' # VGA
#     xrandr --current | grep "^$PORT connected" >/dev/null
#     if [[ $? == 0 ]]; then
#         OUTPUT=$PORT
#     fi

#     PORT='eDP1' # Display port
#     xrandr --current | grep "^$PORT connected" >/dev/null
#     if [[ $? == 0 ]]; then
#         OUTPUT=$PORT
#     fi

# fi

# if [[ ! -z $SECONDARY ]]; then
#     i3-msg workspace 11
#     i3-msg rename workspace 11 to "11: "
#     i3-msg move workspace to output $SECONDARY
# fi
# i3-msg workspace 10
# (skype &>/dev/null &)
# sleep 5
# i3-msg rename workspace 10 to "10: "
# i3-msg move workspace to output $OUTPUT
# i3-msg workspace 9
# (evolution &>/dev/null &)
# sleep 5
# i3-msg rename workspace 9 to "9: "
# i3-msg move workspace to output $OUTPUT
# i3-msg workspace 8
# i3-msg rename workspace 8 to "8: 8"
# i3-msg move workspace to output $OUTPUT
# i3-msg workspace 7
# i3-msg rename workspace 7 to "7: 7"
# i3-msg move workspace to output $OUTPUT
# i3-msg workspace 6
# i3-msg rename workspace 6 to "6: 6"
# i3-msg move workspace to output $OUTPUT
# i3-msg workspace 5
# i3-msg rename workspace 5 to "5: db"
# i3-msg move workspace to output $OUTPUT
# i3-msg workspace 4
# i3-msg rename workspace 4 to "4: code"
# i3-msg move workspace to output $OUTPUT
# i3-msg workspace 3
# (krusader &>/dev/null &)
# sleep 5
# i3-msg rename workspace 3 to "3: files"
# i3-msg move workspace to output $OUTPUT
# i3-msg workspace 2
# (gnome-terminal &>/dev/null &)
# sleep 5
# i3-msg rename workspace 2 to "2: terminal"
# i3-msg move workspace to output $OUTPUT
# i3-msg workspace 1
# (vivaldi &>/dev/null &)
# sleep 5
# i3-msg rename workspace 1 to "1: browser"
# i3-msg move workspace to output $OUTPUT

