hotkeys:
  profile: {}
  shell: {}
ssh: {}
terminal:
  colorScheme:
    name: Solarized Light LT
    foreground: '#839496'
    background: '#fdf6e3'
    cursor: 'rgba(101, 123, 131, 0.4)'
    colors:
      - '#fdf6e3'
      - '#cb4b16'
      - '#859900'
      - '#b58900'
      - '#268bd2'
      - '#6c71c4'
      - '#2aa198'
      - '#657b83'
      - '#586e75'
      - '#cb4b16'
      - '#859900'
      - '#b58900'
      - '#268bd2'
      - '#6c71c4'
      - '#2aa198'
      - '#ffffff'
      - '#839496'
  font: Fira Mono
  fontSize: 18
  ligatures: false
  background: colorScheme
  cursorBlink: false
  cursor: block
  environment: {}
  profile: zsh
  rightClick: paste
  autoOpen: true
  copyOnSelect: true
  frontend: xterm
appearance:
  theme: Paper
  frame: thin
  dock: 'off'
enableAnalytics: true
enableWelcomeTab: false
pluginBlacklist:
  - ssh
  - scrollbar
  - title-control
titleControl: {}
