#!/usr/bin/env bash

echo "=================================================="
echo "Setup directories"
echo "=================================================="

# Remove unnecessary directories from home
[ -d Desktop   ] && rmdir ~/Desktop
[ -d Documents ] && rmdir ~/Documents
[ -d Downloads ] && rmdir ~/Downloads
[ -d Music     ] && rmdir ~/Music
[ -d Pictures  ] && rmdir ~/Pictures
[ -d Public    ] && rmdir ~/Public
[ -d Templates ] && rmdir ~/Templates
[ -d Videos    ] && rmdir ~/Videos

echo "Unnecessary directories removed"

# Make useful directories inside home
mkdir -p ~/bin
mkdir -p ~/opt
mkdir -p ~/sandbox

# Prepare dirs for vim
mkdir -p ~/.vim
mkdir -p ~/.vim/backups
mkdir -p ~/.vim/undos

# Prepare directories for mounting partitions
if [[ $(hostname) == 'lukas-pc-ubuntu' ]]; then
    sudo mkdir -p /media/data
    sudo mkdir -p /media/backup_hdd_320
    sudo mkdir -p /media/backup_hdd_500
    sudo mkdir -p /media/zalohy_tucanek
    sudo mkdir -p /media/spolecne_uloziste
fi

echo "Useful directories created"

# Symlink data directories
if [[ $(hostname) == 'lukas-pc-ubuntu' ]]; then
    HOME_DIR=/media/data
    ln -sfn ${HOME_DIR}/code ~/code
    ln -sfn ${HOME_DIR}/fotky ~/fotky
    ln -sfn ${HOME_DIR}/grafika ~/grafika
    ln -sfn ${HOME_DIR}/hry ~/hry
    ln -sfn ${HOME_DIR}/hudba ~/hudba
    ln -sfn ${HOME_DIR}/informace ~/informace
    ln -sfn ${HOME_DIR}/moje ~/moje
    ln -sfn ${HOME_DIR}/pc ~/pc
    ln -sfn ${HOME_DIR}/skaut ~/skaut
    ln -sfn ${HOME_DIR}/tasks ~/tasks
    ln -sfn ${HOME_DIR}/web ~/web
elif [[ $(hostname) == 'lt-nb-ubuntu' ]]; then
    MOUNT_DIR=/media/data
    ln -sfn ${MOUNT_DIR}/work ~/work
    HOME_DIR=${MOUNT_DIR}/Users/Lukas
    ln -sfn ${HOME_DIR}/down ~/down
    ln -sfn ${HOME_DIR}/tasks ~/tasks
    ln -sfn ${HOME_DIR}/unicorn ~/unicorn
    ln -sfn ${HOME_DIR}/installations ~/installations
    ln -sfn ${HOME_DIR}/materials ~/materials
    ln -sfn ${HOME_DIR}/workspaces ~/workspaces
    ln -sfn ${HOME_DIR}/virtuals ~/virtuals
fi

echo "Data directories symlinked"
