#!/usr/bin/env bash

# =================================================================
#                           Functions
# =================================================================

log() {
    echo "=================================================="
    echo "Installing $1"
    echo "=================================================="
}


# =================================================================
#                        Prepare sources
# =================================================================

# Google Chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

# Skype
sudo add-apt-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner"

# Infinality for better fonts
sudo add-apt-repository ppa:no1wantdthisname/ppa


# =================================================================
#                      Install apt packages
# =================================================================

sudo apt-get update

while read package; do
    [[ "$line" =~ ^#.*$ ]] && continue # skip commented lines
    log "apt package $package"
    sudo apt-get install -y "$package"
done < config/apt-packages.txt


# =================================================================
#                      Custom applications
# =================================================================

cd ~/opt

log 'vim'
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall

log 'gsettings-info'
git clone https://github.com/jmatsuzawa/gsettings-info
ln -sf ~/opt/gsettings-info/gsettings-info ~/bin/gsettings-info

log 'xkblayout-state'
git clone https://github.com/nonpop/xkblayout-state.git
cd xkblayout-state
make
cd ~/opt
ln -sf ~/opt/xkblayout-state/xkblayout-state ~/.i3/scripts/xkblayout-state

log 'fzf'
git clone --depth 1 https://github.com/junegunn/fzf.git
fzf/install

log 'git-credential-helper'
git clone git://github.com/pah/git-credential-helper.git
BACKEND=gnome-keyring
cd git-credential-helper/$BACKEND
make
cp git-credential-$BACKEND ~/bin/
cd ~/opt

log 'fasd'
tar zxv < <(wget -q -O - https://github.com/clvv/fasd/archive/1.0.1.tar.gz)
cd fasd-1.0.1
sudo make install
cd ~/opt

log 'vivaldi'
git clone https://gist.github.com/b5aca855f2d05ba14836.git vivaldi-install
cd vivaldi-install
sudo sh install-vivaldi.sh --snapshot
sudo mv /usr/local/bin/vivaldi-snapshot /usr/local/bin/vivaldi
cd ~/opt

log 'antibody'
curl -s https://raw.githubusercontent.com/getantibody/installer/master/install | bash -s


# =================================================================
#                        Python packages
# =================================================================
log "pip packages"
pip install -r config/python-packages.txt


# =================================================================
#                        NodeJS packages
# =================================================================
while read package; do
    [[ "$line" =~ ^#.*$ ]] && continue # skip commented lines
    log "npm package $package"
    npm install -g "$package"
done < config/nodejs-packages.txt
