#!/usr/bin/env bash

echo
echo "=================================================="
echo "Configuring programs"
echo "=================================================="

# Zsh
if which zsh >/dev/null 2>&1; then
    sudo chsh -s /usr/bin/zsh
fi

if [[ $WSL != true ]]; then

  . ~/dotfiles/install/configure_gnome.sh

fi # WSL != true
