#!/usr/bin/env bash

echo "=================================================="
echo "Setup Gnome"
echo "=================================================="

# =================================================================
#                          Gnome desktop
# =================================================================

# disable fancy gnome animations
gsettings set org.gnome.desktop.interface enable-animations false

# disable cursor blinking
gsettings set org.gnome.desktop.interface cursor-blink false

# do not accelerate mouse cursor
gsettings set org.gnome.desktop.peripherals.mouse speed "-1"

echo "Gsettings updated"

# =================================================================
#                         Gnome terminal
# =================================================================

# Import terminal settings
#dconf load /org/gnome/terminal/ < ~/dotfiles/install/config/gnome-terminal.dconf
#echo "Gnome-terminal settings loaded" 

# =================================================================
#                           Mime types
# =================================================================

xdg-mime default vivaldi-stable.desktop text/html
xdg-mime default vivaldi-stable.desktop x-scheme-handler/http
xdg-mime default vivaldi-stable.desktop x-scheme-handler/https
xdg-mime default vivaldi-stable.desktop x-scheme-handler/about

xdg-mime default vim.desktop text/plain

xdg-mime default gthumb.desktop image/bpm
xdg-mime default gthumb.desktop image/gif
xdg-mime default gthumb.desktop image/ico
xdg-mime default gthumb.desktop image/jpeg
xdg-mime default gthumb.desktop image/jpg
xdg-mime default gthumb.desktop image/png
xdg-mime default gthumb.desktop image/tiff

echo "Mime types set"

# =================================================================
#                             Theme
# =================================================================

# This may not work, additional manual setup in lxappearance will probably be needed
# shell theme
gsettings set org.gnome.shell.extensions.user-theme name "Adwaita"
# cursor theme
gsettings set org.gnome.desktop.interface cursor-theme "DMZ-White"
# gtk theme
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita"
# icon theme
gsettings set org.gnome.desktop.interface icon-theme "Adwaita"


# Set GTK theme for Qt apps
if grep -Fxq "style=GTK+" ~/.config/Trolltech.conf >/dev/null 2>&1
then
    : # "GTK theme for Qt apps already set"
else
    echo "[Qt]" >> ~/.config/Trolltech.conf
    echo "style=GTK+" >> ~/.config/Trolltech.conf
    echo "GTK theme for Qt apps set"
fi

echo "Gnome theme updated"

