#!/bin/bash

# ===== Prepare sources =====

# Google Chrome
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

# Skype
sudo add-apt-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner"

# Infinality for better fonts
sudo add-apt-repository ppa:no1wantdthisname/ppa


# ===== Install apt packages =====

sudo apt-get update

PACKAGES=(
    artha
    compton
    curl
    dict
    dict-gcide
    dict-freedict-eng-ces
    dict-freedict-ces-eng
    dos2unix
    feh
    fontconfig-infinality
    freemind
    git
    gimp
    gnuplot
    google-chrome-stable
    gpick
    gthumb
    i3
    i3blocks
    inkscape
    jabref
    keepass2
    kdeconnect
    krusader
    # libappindicator1
    # libgnome-keyring-dev
    # libindicator7
    # libxss1
    # lyx
    lxappearance
    nautilus-dropbox
    neovim
    network-manager-pptp
    network-manager-vpnc
    nodejs
    numlockx
    npm
    openvpn
    # python
    # python3-dev
    # python3-pip
    # python-dbus
    # python-dev
    # python-gtk2
    # python-pip
    # python-setuptools
    # python-wnck
    # python-xlib
    remmina
    rofi
    scrot
    silversearcher-ag
    skype
    tmux
    trash-cli
    tree
    umlet
    virtualbox
    vagrant
    # viking
    vim-gtk
    vlc
    wmctrl
    xbindkeys
    xdotool
    zsh
)

log() {
    echo "=================================================="
    echo "Installing $1"
    echo "=================================================="
}

for package in ${PACKAGES[@]}; do
    log $package
    sudo apt-get install -y $package
done


# ===== Custom applications =====

cd ~/opt

log 'vim'
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall

log 'gsettings-info'
git clone https://github.com/jmatsuzawa/gsettings-info
ln -sf ~/opt/gsettings-info/gsettings-info ~/bin/gsettings-info

log 'xkblayout-state'
git clone https://github.com/nonpop/xkblayout-state.git
cd xkblayout-state
make
cd ~/opt
ln -sf ~/opt/xkblayout-state/xkblayout-state ~/.i3/scripts/xkblayout-state

log 'fzf'
git clone --depth 1 https://github.com/junegunn/fzf.git
fzf/install

log 'git-credential-helper'
git clone git://github.com/pah/git-credential-helper.git
BACKEND=gnome-keyring
cd git-credential-helper/$BACKEND
make
cp git-credential-$BACKEND ~/bin/
cd ~/opt

log 'fasd'
tar zxv < <(wget -q -O - https://github.com/clvv/fasd/archive/1.0.1.tar.gz)
cd fasd-1.0.1
sudo make install
cd ~/opt

log 'vivaldi'
git clone https://gist.github.com/b5aca855f2d05ba14836.git vivaldi-install
cd vivaldi-install
sudo sh install-vivaldi.sh --snapshot
sudo mv /usr/local/bin/vivaldi-snapshot /usr/local/bin/vivaldi
cd ~/opt

log 'antibody'
curl -s https://raw.githubusercontent.com/getantibody/installer/master/install | bash -s


cd

