#!/usr/bin/env bash

# Remove unnecessary directories from home
[ -d Desktop   ] && rmdir ~/Desktop
[ -d Documents ] && rmdir ~/Documents
[ -d Downloads ] && rmdir ~/Downloads
[ -d Music     ] && rmdir ~/Music
[ -d Pictures  ] && rmdir ~/Pictures
[ -d Public    ] && rmdir ~/Public
[ -d Templates ] && rmdir ~/Templates
[ -d Videos    ] && rmdir ~/Videos

# Make useful directories inside home
mkdir -p ~/bin 
mkdir -p ~/down 
mkdir -p ~/opt 
mkdir -p ~/sandbox 
mkdir -p ~/tasks

# Prepare dirs for vim
mkdir -p ~/.vim 
mkdir -p ~/.vim/backups 
mkdir -p ~/.vim/undos

# Prepare directory for mounting data partition
sudo mkdir -p /media/data

# Symlink data directories
if [[ $PLACE == 'home' ]]; then
    HOME_DIR=/media/data/Users/Lukas
    ln -s ${HOME_DIR}/dev ~/code
    ln -s ${HOME_DIR}/Fotky ~/fotky
    ln -s ${HOME_DIR}/Grafika ~/grafika
    ln -s ${HOME_DIR}/Hry ~/hry
    ln -s ${HOME_DIR}/Hudba ~/hudba
    ln -s ${HOME_DIR}/Informace ~/informace
    ln -s ${HOME_DIR}/Moje ~/moje
    ln -s ${HOME_DIR}/PC ~/pc
    ln -s ${HOME_DIR}/Skaut ~/skaut
    ln -s ${HOME_DIR}/Web ~/web
elif [[ $PLACE == 'work' ]]; then
    MOUNT_DIR=/media/data
    ln -s ${MOUNT_DIR}/work ~/work
    HOME_DIR=${MOUNT_DIR}/Users/Lukas
    ln -s ${HOME_DIR}/tasks ~/tasks
    ln -s ${HOME_DIR}/unicorn ~/unicorn
    ln -s ${HOME_DIR}/installations ~/installations
    ln -s ${HOME_DIR}/materials ~/materials
    ln -s ${HOME_DIR}/workspaces ~/workspaces
    ln -s ${HOME_DIR}/virtuals ~/virtuals
fi

