-- https://github.com/ESSO0428/nvim-html-css
-- {
--   enable_on = {
--     "htmldjango",
--     "html",
--     "php",
--   }, -- set the file types you want the plugin to work on
--   enable_file_patterns = { "*.html" }, -- set the file patterns you want the plugin to work on file patterns (default is  *.html)
--   -- enable_file_patterns = { "*.html", "*.php" }
--   file_extensions = { "css", "sass", "less" }, -- set the local filetypes from which you want to derive classes
--   style_sheets = {
--     -- example of remote styles, only css no js for now
--     "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css",
--     "https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css",
--   },
-- }
