#!/usr/bin/env bash

# 1. arg = executable app name
# 2. arg = window class name

if [ $# -lt 2 ]; then
    notify-send -u NORMAL "Not enought arguments for $0 script."
    exit 1
fi

if [ $(wmctrl -l | grep -ic "$2") -gt 0 ]
then
    i3-msg "[class=\"(?i)$2\"] move workspace current"
else
    $1 &
fi
