#!/usr/bin/env bash

lock() {
    i3lock --color "#504945"
}

close_applications() {
    xdotool search --class ".*" | xargs -inum xdotool getwindowpid num 2> /dev/null | grep "^[0-9]" | uniq -u | xargs kill
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        close_applications
        sleep 5
        i3-msg exit
        ;;
    suspend)
        if [[ $(hostname) == 'lukas-pc-ubuntu' ]]; then
            systemctl suspend
        else
            lock && systemctl suspend
        fi
        ;;
    hibernate)
        if [[ $(hostname) == 'lukas-pc-ubuntu' ]]; then
            systemctl hibernate
        else
            lock && systemctl hibernate
        fi
        ;;
    reboot)
        close_applications
        sleep 5
        systemctl reboot
        ;;
    shutdown)
        close_applications
        sleep 5
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
