#!/usr/bin/env bash

handle_selection() {
    if [ -n "$1" ]; then
        pid=$(echo "$1" | awk '{print $1}')
        if ps -p $pid > /dev/null; then
            cmd=$(echo "$1" | awk 'OFS="";$1=$2=$3="";{print}')
            kill $pid
            notify-send -u low "Process killed" "pid: $pid \ncmd:${cmd:0:50}"
        fi
    fi
}

handle_selection "$( \
    ps -eo pid,user,start_time,cmd --sort -start_time \
    | rofi -dmenu -i -fuzzy -p "kill: " )"
