#!/usr/bin/env bash

handle_selection() {
    if [[ "$1" ]]; then
        name="$1"
        if [[ -f "$name" ]]; then
            ( $TERMINAL -e "$EDITOR $name" &>/dev/null & )
        else
            notify-send -u low "File" "No file called $name."
        fi
    fi
}

handle_selection "$(locate_text_files | rofi -dmenu -i -fuzzy -p "file: ")"
